### ISSUE TITLE
Add option to display desktop name instead of number

### ISSUE THREAD

**Issue by rigopoui** [tilorenz/compact_pager#10]
Currently the widget shows the desktop number. I like to use other symbols/names for my desktops. Is it possible to add support for this?

**Comment by tilorenz** [comment]
In principle yes, but I think it would need some rewriting so not sure I'll get around to it right away

**Comment by adam-tj** [comment]
With this feature this plasmoid would be perfect!

**Comment by tilorenz** [comment]
ok, I implemented this, but it was a bit of a rewrite, so it would be cool if some of you could test it before I update the plasmoid on the store.
one issue I found myself is that when you add a new desktop, the name is empty until you edit it. I have no idea why that happens though :/

**Comment by adam-tj** [comment]
I can test it once I am back from holiday

**Comment by tilorenz** [comment]
It seemed to work fine for me; I made a release
