### ISSUE TITLE
Add indicator showing whether the workspace is not empty

### ISSUE THREAD

**Issue by mphe** [tilorenz/compact_pager#11]
First, thank you for this nice plugin, much better than the default.

Would it be possible to add an optional indicator to each field showing whether the workspace is not empty?

For example, in Awesome WM's default config, there is a small rectangle in the top left corner when the respective workspace is not empty.
Here is a screenshot: https://en.wikipedia.org/wiki/Awesome_%28window_manager%29#/media/File:Awesome_screenshot.png

**Comment by tilorenz** [comment]
Happy you like it. Yes, that should be possible, but may need some time

**Comment by tilorenz** [comment]
Alright, I got it working. Any ideas/suggestions on the styling?
![rect_full](https://github.com/tilorenz/compact_pager/assets/59516401/8cf19902-0d4a-439f-b76a-e77023057a27)
![rect_nr](https://github.com/tilorenz/compact_pager/assets/59516401/ab90bbb3-6bb0-461e-a90b-6a9291776a77)
![under_full](https://github.com/tilorenz/compact_pager/assets/59516401/d9fd6085-9577-46cc-92bc-0bca5f66a004)

**Comment by mphe** [comment]
Great work, thank you!
Personally, I prefer the the box style rather than the underline style.
An option to specify the roundness similar to the normal border radius would be nice so it can also match the underlying style. It's also fine if it uses the existing border radius setting instead of adding another one.
It seems like the tab automatically expands in width to fit the marker. Is it possible to have an option to keep a fixed width and let it overlap if needed?

**Comment by tilorenz** [comment]
> It seems like the tab automatically expands in width to fit the marker. Is it possible to have an option to keep a fixed width and let it overlap if needed?

I wasn't super happy with how much larger it made the number boxes either. I removed the additional width now, the clipping isn't super nice either but I guess it's ok...

If you want to check it out I have it on the `windicator` branch

**Comment by mphe** [comment]
Just tested it and the clipping is fine in my case.
![Screenshot_20240427_135510](https://github.com/tilorenz/compact_pager/assets/7116001/68cf1490-3102-452f-983f-8e8d703336dc)
Maybe add an option to specify the size of the box so people can reduce the size to reduce clipping.

**Comment by tilorenz** [comment]
Since it's fine for you I think I'll just release it as is for now; I can make an option if and when people complain. This thing has already gotten way to configurable over the years, lol

**Comment by mphe** [comment]
Alright, thank you for your time!
IMO there is no such thing as too configurable :)

**Comment by Diagon** [comment]
First of all, thanks for the great widget!

I know this has been closed, but it would have been amazing to be able to set "Inactive with windows" background color for much cleaner styling.

**Comment by tilorenz** [comment]
Alright, implemented it.
