### ISSUE TITLE
Add Plasma 6 version to KDE store

### ISSUE THREAD

**Issue by MorsMortium** [tilorenz/compact_pager#13]
I see that it was ported to Plasma 6. It would be cool, if it was downloadable. Its possible to have multiple files for one store item, and then users can choose. The names could contain which Plasma version it is for.

**Comment by tilorenz** [comment]
the plasma 5 version has its own store page, because there are separate categories for p5 and p6 addons. currently, store.kde.org seems to be down but both versions should be downloadable once it's up again.

**Comment by MorsMortium** [comment]
Have found it! There is a small KDE bug, that I still had the Plasma 5 version installed, and so it errored out when I searched and installed the new one, and so i thought it was the old version. Remove and reinstall solved it
