### ISSUE TITLE
Freezes Plasma

### ISSUE THREAD

**Issue by luaVolk** [tilorenz/compact_pager#14]
Plasma: 6.1.2
Qt: 6.7.2

All of plasma freezes when I switch to full layout.
journal is filled with the following  warning:
```
...
plasmashell[454948]: file:///home/volk/.local/share/plasma/plasmoids/com.github.tilorenz.compact_pager/contents/ui/main.qml:105:25: QML ReprLayout: ReprLayout called polish() inside updatePolish() of ReprLayout
plasmashell[454948]: file:///home/volk/.local/share/plasma/plasmoids/com.github.tilorenz.compact_pager/contents/ui/main.qml:105:25: QML ReprLayout: possible QQuickItem::polish() loop
...
```

**Comment by tilorenz** [comment]
Ok, I'm on the same versions and can't reproduce. Can you give me some more info about when exactly this triggers?

**Comment by luaVolk** [comment]
It triggers freezes as soon as I set it
![Screenshot_20240712_133137](https://github.com/user-attachments/assets/20fbf75b-7cff-4477-87c8-678779d3707d)
If I click apply there it will freeze, and plasma wont start if I log out and back in again.
Had to manually remove the setting from the config file.

**Comment by hyknn** [comment]
This happens to me too, but it happens when I click on the widget

**Comment by tilorenz** [comment]
Ok, I now managed to reproduce it. Can you try the fixFreeze branch?

**Comment by ikopytko** [comment]
Hi, I can confirm, that branch fixFreeze actually fixes the freeze. I got the same problem on Plasma 6.2.1

**Comment by tilorenz** [comment]
Great, thanks for confirming! In the meantime, I released a version with the fix, so you shouldn't get it from the kde store version anymore either.
