### ISSUE TITLE
Ability to set inactive background color

### ISSUE THREAD

**Issue by MorsMortium** [tilorenz/compact_pager#2]
Currently the widget hardcodes inactive background color as a darker background color. It would be nice, if it had a checkmark/color selector in its appearance tab, to also specify it, if needed.

**Comment by tilorenz** [comment]
Ok, i made a PR: #3 
Does this work for you?

**Comment by MorsMortium** [comment]
It works as a standalone widget, but does not, when added to a latte panel (and i have no idea about default panel). The previous active only worked on latte too.

**Comment by tilorenz** [comment]
Uhm, it works for me in a standard panel, no idea what latte does. Did you log out and back in again?

I added a test label to the general config so you can easily check if you're using the correct version.

**Comment by MorsMortium** [comment]
Okay, relogin fixed it
