### ISSUE TITLE
Vertical layout does not seem to work on Plasma 6

### ISSUE THREAD

**Issue by lindely** [tilorenz/compact_pager#9]
I've used this applet on Plasma 5 for a long time and was happy to see it ported to Plasma 6. However, I cannot get the vertical layout to work. I have a vertical panel containing the applet, but the applet always shows my four virtual desktops from left to right. I tried using one row with four desktops and four rows with one desktop each, but the result always ends up the same:

![Compact pager - 1 row](https://github.com/tilorenz/compact_pager/assets/19426224/60a7a594-5694-4c29-957c-62f0210117e5)
![Compact pager - 4 rows](https://github.com/tilorenz/compact_pager/assets/19426224/3276afb8-7655-4e26-a523-4b95b4ea9013)

Am I missing something obvious (apologies if I do) or is this a bug of some sorts?

**Comment by tilorenz** [comment]
Huh, I didn't touch the layout code while porting, but I can reproduce. I'll look into it.

**Comment by tilorenz** [comment]
I think I now have a solution that works ok, can you try out the vlayout branch?

**Comment by lindely** [comment]
I tried it and it works when setting virtual desktops to four rows:

![4rows](https://github.com/tilorenz/compact_pager/assets/19426224/5733882f-09b1-4a7e-b58f-20ea8738d9d1)

Not the same machine as the one in the first post, but that shouldn't be an issue I assume.

Thank you for the fix! I am unsure if I should close this issue or not so I'll take the cautious approach and leave it for you to close.

**Comment by tilorenz** [comment]
Great! I'll close this and make a release then.
